//
//  StrokeView.swift
//  CreativityHomework
//
//  Created by Антон Пеньков on 18.03.2024.
//

import SwiftUI

struct StrokeView: View {
    @State private var percentage = 1.0
    
    var body: some View {
        ZStack {
            GeometryReader { geometry in
                let width = geometry.size.width
                let height = width * 7 / 5
                
                VStack {
                    Spacer(minLength: 105)
                    Image("Bouguereau")
                        .resizable()
                        .frame(width: width, height: height)
                    Spacer()
                }
                
                Path { path in
                    path.move(to: CGPoint(x: 165, y: 290))
                    path.addLine(to: CGPoint(x: 165, y: 270))
                    path.addLine(to: CGPoint(x: 160, y: 255))
                    path.addLine(to: CGPoint(x: 150, y: 250))
                    path.addLine(to: CGPoint(x: 140, y: 245))
                    path.addLine(to: CGPoint(x: 130, y: 245))
                    path.addLine(to: CGPoint(x: 115, y: 250))
                    path.addLine(to: CGPoint(x: 115, y: 240))
                    path.addLine(to: CGPoint(x: 115, y: 250))
                    path.addLine(to: CGPoint(x: 110, y: 260))
                    path.addLine(to: CGPoint(x: 100, y: 270))
                    path.addLine(to: CGPoint(x: 90, y: 265))
                    path.addLine(to: CGPoint(x: 90, y: 250))
                    path.addLine(to: CGPoint(x: 100, y: 240))
                    path.addLine(to: CGPoint(x: 110, y: 240))
                    path.addLine(to: CGPoint(x: 115, y: 240))
                    path.addLine(to: CGPoint(x: 110, y: 230))
                    path.addLine(to: CGPoint(x: 110, y: 230))
                    path.addLine(to: CGPoint(x: 100, y: 220))
                    path.addLine(to: CGPoint(x: 90, y: 220))
                    path.addLine(to: CGPoint(x: 80, y: 225))
                    path.addLine(to: CGPoint(x: 75, y: 230))
                    path.addLine(to: CGPoint(x: 70, y: 250))
                    path.addLine(to: CGPoint(x: 60, y: 270))
                    path.addLine(to: CGPoint(x: 60, y: 275))
                    path.addLine(to: CGPoint(x: 90, y: 260))
                    path.addLine(to: CGPoint(x: 60, y: 275))
                    path.addLine(to: CGPoint(x: 50, y: 290))
                    path.addLine(to: CGPoint(x: 35, y: 295))
                    path.addLine(to: CGPoint(x: 25, y: 275))
                    path.addLine(to: CGPoint(x: 25, y: 265))
                    path.addLine(to: CGPoint(x: 20, y: 260))
                    path.addLine(to: CGPoint(x: 10, y: 260))
                    path.addLine(to: CGPoint(x: 10, y: 275))
                    path.addLine(to: CGPoint(x: 15, y: 280))
                    path.addLine(to: CGPoint(x: 20, y: 300))
                    path.addLine(to: CGPoint(x: 25, y: 315))
                    path.addLine(to: CGPoint(x: 35, y: 315))
                    path.addLine(to: CGPoint(x: 45, y: 310))
                    path.addLine(to: CGPoint(x: 70, y: 290))
                    path.addLine(to: CGPoint(x: 85, y: 310))
                    path.addLine(to: CGPoint(x: 100, y: 310))
                    path.addLine(to: CGPoint(x: 110, y: 300))
                    path.addLine(to: CGPoint(x: 125, y: 305))
                    path.addLine(to: CGPoint(x: 135, y: 300))
                    path.addLine(to: CGPoint(x: 125, y: 305))
                    path.addLine(to: CGPoint(x: 110, y: 300))
                    path.addLine(to: CGPoint(x: 100, y: 310))
                    path.addLine(to: CGPoint(x: 85, y: 310))
                    path.addLine(to: CGPoint(x: 85, y: 310))
                    path.addLine(to: CGPoint(x: 70, y: 325))
                    path.addLine(to: CGPoint(x: 65, y: 335))
                    path.addLine(to: CGPoint(x: 40, y: 360))
                    path.addLine(to: CGPoint(x: 40, y: 380))
                    path.addLine(to: CGPoint(x: 50, y: 390))
                    path.addLine(to: CGPoint(x: 65, y: 385))
                    path.addLine(to: CGPoint(x: 90, y: 365))
                    path.addLine(to: CGPoint(x: 95, y: 360))
                    path.addLine(to: CGPoint(x: 90, y: 355))
                    path.addLine(to: CGPoint(x: 95, y: 360))
                    path.addLine(to: CGPoint(x: 100, y: 360))
                    path.addLine(to: CGPoint(x: 105, y: 360))
                    path.addLine(to: CGPoint(x: 100, y: 360))
                    path.addLine(to: CGPoint(x: 90, y: 390))
                    path.addLine(to: CGPoint(x: 85, y: 430))
                    path.addLine(to: CGPoint(x: 90, y: 450))
                    path.addLine(to: CGPoint(x: 85, y: 470))
                    path.addLine(to: CGPoint(x: 85, y: 500))
                    path.addLine(to: CGPoint(x: 80, y: 520))
                    path.addLine(to: CGPoint(x: 80, y: 535))
                    path.addLine(to: CGPoint(x: 95, y: 535))
                    path.addLine(to: CGPoint(x: 100, y: 525))
                    path.addLine(to: CGPoint(x: 95, y: 515))
                    path.addLine(to: CGPoint(x: 95, y: 500))
                    path.addLine(to: CGPoint(x: 105, y: 470))
                    path.addLine(to: CGPoint(x: 110, y: 450))
                    path.addLine(to: CGPoint(x: 105, y: 430))
                    path.addLine(to: CGPoint(x: 110, y: 410))
                    path.addLine(to: CGPoint(x: 105, y: 400))
                    path.addLine(to: CGPoint(x: 105, y: 380))
                    path.addLine(to: CGPoint(x: 110, y: 370))
                    path.addLine(to: CGPoint(x: 125, y: 350))
                    path.addLine(to: CGPoint(x: 135, y: 355))
                    path.addLine(to: CGPoint(x: 140, y: 345))
                    path.addLine(to: CGPoint(x: 135, y: 340))
                    path.addLine(to: CGPoint(x: 130, y: 340))
                    path.addLine(to: CGPoint(x: 125, y: 350))
                    path.addLine(to: CGPoint(x: 135, y: 320))
                    path.addLine(to: CGPoint(x: 135, y: 300))
                    path.addLine(to: CGPoint(x: 135, y: 285))
                    path.addLine(to: CGPoint(x: 130, y: 275))
                    path.addLine(to: CGPoint(x: 130, y: 265))
                    path.addLine(to: CGPoint(x: 145, y: 265))
                    path.addLine(to: CGPoint(x: 150, y: 280))
                    path.addLine(to: CGPoint(x: 150, y: 300))
                    path.addLine(to: CGPoint(x: 145, y: 305))
                    path.addLine(to: CGPoint(x: 145, y: 315))
                    path.addLine(to: CGPoint(x: 145, y: 310))
                    path.addLine(to: CGPoint(x: 135, y: 320))
                    path.addLine(to: CGPoint(x: 145, y: 310))
                    path.addLine(to: CGPoint(x: 145, y: 315))
                    path.addLine(to: CGPoint(x: 150, y: 320))
                    path.addLine(to: CGPoint(x: 165, y: 305))
                    path.addLine(to: CGPoint(x: 160, y: 300))
                    path.addLine(to: CGPoint(x: 155, y: 290))
                    path.addLine(to: CGPoint(x: 170, y: 290))
                    path.addLine(to: CGPoint(x: 175, y: 295))
                    path.addLine(to: CGPoint(x: 210, y: 300))
                    path.addLine(to: CGPoint(x: 230, y: 285))
                    path.addLine(to: CGPoint(x: 245, y: 275))
                    path.addLine(to: CGPoint(x: 250, y: 265))
                    path.addLine(to: CGPoint(x: 260, y: 260))
                    path.addLine(to: CGPoint(x: 260, y: 250))
                    path.addLine(to: CGPoint(x: 265, y: 245))
                    path.addLine(to: CGPoint(x: 265, y: 225))
                    path.addLine(to: CGPoint(x: 270, y: 220))
                    path.addLine(to: CGPoint(x: 265, y: 215))
                    path.addLine(to: CGPoint(x: 245, y: 220))
                    path.addLine(to: CGPoint(x: 235, y: 240))
                    path.addLine(to: CGPoint(x: 235, y: 280))
                    path.addLine(to: CGPoint(x: 235, y: 240))
                    path.addLine(to: CGPoint(x: 245, y: 220))
                    path.addLine(to: CGPoint(x: 265, y: 215))
                    path.addLine(to: CGPoint(x: 270, y: 220))
                    path.addLine(to: CGPoint(x: 275, y: 230))
                    path.addLine(to: CGPoint(x: 280, y: 235))
                    path.addLine(to: CGPoint(x: 285, y: 250))
                    path.addLine(to: CGPoint(x: 275, y: 255))
                    path.addLine(to: CGPoint(x: 280, y: 260))
                    path.addLine(to: CGPoint(x: 285, y: 250))
                    path.addLine(to: CGPoint(x: 285, y: 245))
                    path.addLine(to: CGPoint(x: 295, y: 235))
                    path.addLine(to: CGPoint(x: 305, y: 215))
                    path.addLine(to: CGPoint(x: 305, y: 200))
                    path.addLine(to: CGPoint(x: 310, y: 170))
                    path.addLine(to: CGPoint(x: 300, y: 155))
                    path.addLine(to: CGPoint(x: 300, y: 145))
                    path.addLine(to: CGPoint(x: 305, y: 140))
                    path.addLine(to: CGPoint(x: 315, y: 150))
                    path.addLine(to: CGPoint(x: 315, y: 155))
                    path.addLine(to: CGPoint(x: 320, y: 165))
                    path.addLine(to: CGPoint(x: 320, y: 210))
                    path.addLine(to: CGPoint(x: 310, y: 240))
                    path.addLine(to: CGPoint(x: 300, y: 260))
                    path.addLine(to: CGPoint(x: 300, y: 275))
                    path.addLine(to: CGPoint(x: 310, y: 285))
                    path.addLine(to: CGPoint(x: 310, y: 295))
                    path.addLine(to: CGPoint(x: 305, y: 300))
                    path.addLine(to: CGPoint(x: 310, y: 305))
                    path.addLine(to: CGPoint(x: 310, y: 335))
                    path.addLine(to: CGPoint(x: 300, y: 345))
                    path.addLine(to: CGPoint(x: 295, y: 335))
                    path.addLine(to: CGPoint(x: 285, y: 330))
                    path.addLine(to: CGPoint(x: 295, y: 305))
                    path.addLine(to: CGPoint(x: 285, y: 290))
                    path.addLine(to: CGPoint(x: 275, y: 285))
                    path.addLine(to: CGPoint(x: 260, y: 285))
                    path.addLine(to: CGPoint(x: 250, y: 300))
                    path.addLine(to: CGPoint(x: 240, y: 300))
                    path.addLine(to: CGPoint(x: 230, y: 320))
                    path.addLine(to: CGPoint(x: 255, y: 320))
                    path.addLine(to: CGPoint(x: 255, y: 325))
                    path.addLine(to: CGPoint(x: 260, y: 330))
                    path.addLine(to: CGPoint(x: 255, y: 325))
                    path.addLine(to: CGPoint(x: 255, y: 320))
                    path.addLine(to: CGPoint(x: 255, y: 305))
                    path.addLine(to: CGPoint(x: 265, y: 300))
                    path.addLine(to: CGPoint(x: 280, y: 305))
                    path.addLine(to: CGPoint(x: 285, y: 315))
                    path.addLine(to: CGPoint(x: 280, y: 325))
                    path.addLine(to: CGPoint(x: 285, y: 330))
                    path.addLine(to: CGPoint(x: 295, y: 335))
                    path.addLine(to: CGPoint(x: 300, y: 345))
                    path.addLine(to: CGPoint(x: 310, y: 335))
                    path.addLine(to: CGPoint(x: 315, y: 340))
                    path.addLine(to: CGPoint(x: 315, y: 340))
                    path.addLine(to: CGPoint(x: 315, y: 355))
                    path.addLine(to: CGPoint(x: 295, y: 355))
                    path.addLine(to: CGPoint(x: 285, y: 365))
                    path.addLine(to: CGPoint(x: 280, y: 390))
                    path.addLine(to: CGPoint(x: 295, y: 385))
                    path.addLine(to: CGPoint(x: 305, y: 390))
                    path.addLine(to: CGPoint(x: 310, y: 385))
                    path.addLine(to: CGPoint(x: 300, y: 380))
                    path.addLine(to: CGPoint(x: 280, y: 360))
                    path.addLine(to: CGPoint(x: 260, y: 355))
                    path.addLine(to: CGPoint(x: 225, y: 355))
                    path.addLine(to: CGPoint(x: 230, y: 345))
                    path.addLine(to: CGPoint(x: 210, y: 355))
                    path.addLine(to: CGPoint(x: 210, y: 340))
                    path.addLine(to: CGPoint(x: 205, y: 335))
                    path.addLine(to: CGPoint(x: 215, y: 330))
                    path.addLine(to: CGPoint(x: 230, y: 320))
                    path.addLine(to: CGPoint(x: 215, y: 330))
                    path.addLine(to: CGPoint(x: 205, y: 335))
                    path.addLine(to: CGPoint(x: 195, y: 330))
                    path.addLine(to: CGPoint(x: 180, y: 335))
                    path.addLine(to: CGPoint(x: 175, y: 325))
                    path.addLine(to: CGPoint(x: 180, y: 315))
                    path.addLine(to: CGPoint(x: 175, y: 305))
                    path.addLine(to: CGPoint(x: 165, y: 305))
                    path.addLine(to: CGPoint(x: 175, y: 305))
                    path.addLine(to: CGPoint(x: 210, y: 315))
                    path.addLine(to: CGPoint(x: 250, y: 290))
                    path.addLine(to: CGPoint(x: 250, y: 300))
                    path.addLine(to: CGPoint(x: 250, y: 290))
                    path.addLine(to: CGPoint(x: 210, y: 315))
                    path.addLine(to: CGPoint(x: 175, y: 305))
                    path.addLine(to: CGPoint(x: 180, y: 315))
                    path.addLine(to: CGPoint(x: 175, y: 325))
                    path.addLine(to: CGPoint(x: 180, y: 335))
                    path.addLine(to: CGPoint(x: 170, y: 355))
                    path.addLine(to: CGPoint(x: 160, y: 335))
                    path.addLine(to: CGPoint(x: 170, y: 355))
                    path.addLine(to: CGPoint(x: 175, y: 345))
                    path.addLine(to: CGPoint(x: 185, y: 345))
                    path.addLine(to: CGPoint(x: 205, y: 355))
                    path.addLine(to: CGPoint(x: 260, y: 355))
                    path.addLine(to: CGPoint(x: 250, y: 360))
                    path.addLine(to: CGPoint(x: 260, y: 375))
                    path.addLine(to: CGPoint(x: 270, y: 370))
                    path.addLine(to: CGPoint(x: 285, y: 375))
                    path.addLine(to: CGPoint(x: 270, y: 385))
                    path.addLine(to: CGPoint(x: 260, y: 400))
                    path.addLine(to: CGPoint(x: 280, y: 390))
                    path.addLine(to: CGPoint(x: 260, y: 400))
                    path.addLine(to: CGPoint(x: 230, y: 405))
                    path.addLine(to: CGPoint(x: 205, y: 390))
                    path.addLine(to: CGPoint(x: 210, y: 375))
                    path.addLine(to: CGPoint(x: 230, y: 370))
                    path.addLine(to: CGPoint(x: 240, y: 375))
                    path.addLine(to: CGPoint(x: 260, y: 370))
                    path.addLine(to: CGPoint(x: 240, y: 375))
                    path.addLine(to: CGPoint(x: 230, y: 370))
                    path.addLine(to: CGPoint(x: 210, y: 375))
                    path.addLine(to: CGPoint(x: 190, y: 370))
                    path.addLine(to: CGPoint(x: 170, y: 375))
                    path.addLine(to: CGPoint(x: 195, y: 390))
                    path.addLine(to: CGPoint(x: 205, y: 390))
                    path.addLine(to: CGPoint(x: 195, y: 390))
                    path.addLine(to: CGPoint(x: 170, y: 375))
                    path.addLine(to: CGPoint(x: 160, y: 360))
                    path.addLine(to: CGPoint(x: 145, y: 355))
                    path.addLine(to: CGPoint(x: 125, y: 360))
                    path.addLine(to: CGPoint(x: 125, y: 375))
                    path.addLine(to: CGPoint(x: 145, y: 385))
                    path.addLine(to: CGPoint(x: 160, y: 395))
                    path.addLine(to: CGPoint(x: 180, y: 400))
                    path.addLine(to: CGPoint(x: 185, y: 395))
                    path.addLine(to: CGPoint(x: 195, y: 400))
                    path.addLine(to: CGPoint(x: 200, y: 405))
                    path.addLine(to: CGPoint(x: 230, y: 405))
                    path.addLine(to: CGPoint(x: 260, y: 400))
                    path.addLine(to: CGPoint(x: 280, y: 390))
                    path.addLine(to: CGPoint(x: 295, y: 385))
                    path.addLine(to: CGPoint(x: 305, y: 390))
                    path.addLine(to: CGPoint(x: 310, y: 385))
                    path.addLine(to: CGPoint(x: 325, y: 400))
                    path.addLine(to: CGPoint(x: 335, y: 405))
                    path.addLine(to: CGPoint(x: 340, y: 395))
                    path.addLine(to: CGPoint(x: 335, y: 385))
                    path.addLine(to: CGPoint(x: 335, y: 370))
                    path.addLine(to: CGPoint(x: 315, y: 355))
                    path.addLine(to: CGPoint(x: 335, y: 370))
                    path.addLine(to: CGPoint(x: 335, y: 385))
                    path.addLine(to: CGPoint(x: 340, y: 395))
                    path.addLine(to: CGPoint(x: 335, y: 405))
                    path.addLine(to: CGPoint(x: 340, y: 420))
                    path.addLine(to: CGPoint(x: 340, y: 440))
                    path.addLine(to: CGPoint(x: 335, y: 460))
                    path.addLine(to: CGPoint(x: 340, y: 480))
                    path.addLine(to: CGPoint(x: 335, y: 500))
                    path.addLine(to: CGPoint(x: 335, y: 510))
                    path.addLine(to: CGPoint(x: 325, y: 530))
                    path.addLine(to: CGPoint(x: 295, y: 560))
                    path.addLine(to: CGPoint(x: 280, y: 575))
                    path.addLine(to: CGPoint(x: 275, y: 600))
                    path.addLine(to: CGPoint(x: 240, y: 640))
                    path.addLine(to: CGPoint(x: 240, y: 655))
                    path.addLine(to: CGPoint(x: 220, y: 655))
                    path.addLine(to: CGPoint(x: 250, y: 595))
                    path.addLine(to: CGPoint(x: 260, y: 580))
                    path.addLine(to: CGPoint(x: 260, y: 565))
                    path.addLine(to: CGPoint(x: 290, y: 520))
                    path.addLine(to: CGPoint(x: 300, y: 515))
                    path.addLine(to: CGPoint(x: 310, y: 520))
                    path.addLine(to: CGPoint(x: 300, y: 515))
                    path.addLine(to: CGPoint(x: 310, y: 495))
                    path.addLine(to: CGPoint(x: 300, y: 515))
                    path.addLine(to: CGPoint(x: 290, y: 520))
                    path.addLine(to: CGPoint(x: 260, y: 565))
                    path.addLine(to: CGPoint(x: 260, y: 580))
                    path.addLine(to: CGPoint(x: 250, y: 595))
                    path.addLine(to: CGPoint(x: 240, y: 615))
                    path.addLine(to: CGPoint(x: 230, y: 595))
                    path.addLine(to: CGPoint(x: 245, y: 590))
                    path.addLine(to: CGPoint(x: 245, y: 595))
                    path.addLine(to: CGPoint(x: 250, y: 545))
                    path.addLine(to: CGPoint(x: 265, y: 525))
                    path.addLine(to: CGPoint(x: 260, y: 510))
                    path.addLine(to: CGPoint(x: 260, y: 480))
                    path.addLine(to: CGPoint(x: 280, y: 450))
                    path.addLine(to: CGPoint(x: 290, y: 445))
                    path.addLine(to: CGPoint(x: 295, y: 435))
                    path.addLine(to: CGPoint(x: 290, y: 445))
                    path.addLine(to: CGPoint(x: 280, y: 430))
                    path.addLine(to: CGPoint(x: 290, y: 410))
                    path.addLine(to: CGPoint(x: 280, y: 415))
                    path.addLine(to: CGPoint(x: 275, y: 430))
                    path.addLine(to: CGPoint(x: 265, y: 430))
                    path.addLine(to: CGPoint(x: 280, y: 450))
                    path.addLine(to: CGPoint(x: 265, y: 430))
                    path.addLine(to: CGPoint(x: 245, y: 420))
                    path.addLine(to: CGPoint(x: 280, y: 415))
                    path.addLine(to: CGPoint(x: 245, y: 420))
                    path.addLine(to: CGPoint(x: 200, y: 415))
                    path.addLine(to: CGPoint(x: 180, y: 400))
                    path.addLine(to: CGPoint(x: 200, y: 415))
                    path.addLine(to: CGPoint(x: 245, y: 420))
                    path.addLine(to: CGPoint(x: 255, y: 430))
                    path.addLine(to: CGPoint(x: 255, y: 440))
                    path.addLine(to: CGPoint(x: 240, y: 435))
                    path.addLine(to: CGPoint(x: 230, y: 420))
                    path.addLine(to: CGPoint(x: 240, y: 435))
                    path.addLine(to: CGPoint(x: 255, y: 440))
                    path.addLine(to: CGPoint(x: 265, y: 450))
                    path.addLine(to: CGPoint(x: 270, y: 465))
                    path.addLine(to: CGPoint(x: 255, y: 485))
                    path.addLine(to: CGPoint(x: 255, y: 465))
                    path.addLine(to: CGPoint(x: 245, y: 455))
                    path.addLine(to: CGPoint(x: 230, y: 455))
                    path.addLine(to: CGPoint(x: 215, y: 440))
                    path.addLine(to: CGPoint(x: 200, y: 420))
                    path.addLine(to: CGPoint(x: 200, y: 415))
                    path.addLine(to: CGPoint(x: 190, y: 410))
                    path.addLine(to: CGPoint(x: 190, y: 440))
                    path.addLine(to: CGPoint(x: 180, y: 440))
                    path.addLine(to: CGPoint(x: 165, y: 395))
                    path.addLine(to: CGPoint(x: 180, y: 440))
                    path.addLine(to: CGPoint(x: 180, y: 450))
                    path.addLine(to: CGPoint(x: 160, y: 450))
                    path.addLine(to: CGPoint(x: 190, y: 450))
                    path.addLine(to: CGPoint(x: 210, y: 455))
                    path.addLine(to: CGPoint(x: 215, y: 440))
                    path.addLine(to: CGPoint(x: 210, y: 455))
                    path.addLine(to: CGPoint(x: 225, y: 465))
                    path.addLine(to: CGPoint(x: 225, y: 450))
                    path.addLine(to: CGPoint(x: 225, y: 465))
                    path.addLine(to: CGPoint(x: 235, y: 490))
                    path.addLine(to: CGPoint(x: 235, y: 510))
                    path.addLine(to: CGPoint(x: 250, y: 505))
                    path.addLine(to: CGPoint(x: 255, y: 480))
                    path.addLine(to: CGPoint(x: 250, y: 505))
                    path.addLine(to: CGPoint(x: 235, y: 510))
                    path.addLine(to: CGPoint(x: 250, y: 540))
                    path.addLine(to: CGPoint(x: 230, y: 535))
                    path.addLine(to: CGPoint(x: 235, y: 510))
                    path.addLine(to: CGPoint(x: 230, y: 535))
                    path.addLine(to: CGPoint(x: 230, y: 545))
                    path.addLine(to: CGPoint(x: 245, y: 570))
                    path.addLine(to: CGPoint(x: 240, y: 580))
                    path.addLine(to: CGPoint(x: 230, y: 575))
                    path.addLine(to: CGPoint(x: 215, y: 545))
                    path.addLine(to: CGPoint(x: 210, y: 540))
                    path.addLine(to: CGPoint(x: 210, y: 515))
                    path.addLine(to: CGPoint(x: 235, y: 490))
                    path.addLine(to: CGPoint(x: 210, y: 515))
                    path.addLine(to: CGPoint(x: 185, y: 525))
                    path.addLine(to: CGPoint(x: 220, y: 555))
                    path.addLine(to: CGPoint(x: 235, y: 590))
                    path.addLine(to: CGPoint(x: 220, y: 585))
                    path.addLine(to: CGPoint(x: 210, y: 560))
                    path.addLine(to: CGPoint(x: 170, y: 540))
                    path.addLine(to: CGPoint(x: 160, y: 570))
                    path.addLine(to: CGPoint(x: 160, y: 585))
                    path.addLine(to: CGPoint(x: 150, y: 585))
                    path.addLine(to: CGPoint(x: 145, y: 580))
                    path.addLine(to: CGPoint(x: 155, y: 565))
                    path.addLine(to: CGPoint(x: 160, y: 535))
                    path.addLine(to: CGPoint(x: 170, y: 540))
                    path.addLine(to: CGPoint(x: 160, y: 535))
                    path.addLine(to: CGPoint(x: 155, y: 520))
                    path.addLine(to: CGPoint(x: 175, y: 500))
                    path.addLine(to: CGPoint(x: 175, y: 490))
                    path.addLine(to: CGPoint(x: 150, y: 490))
                    path.addLine(to: CGPoint(x: 130, y: 470))
                    path.addLine(to: CGPoint(x: 130, y: 450))
                    path.addLine(to: CGPoint(x: 110, y: 410))
                }
                .trim(from: 0, to: percentage)
                .stroke(lineWidth: 2)
                .foregroundStyle(.white)
                .animation(.bouncy, value: percentage)
            }
            
            VStack {
                Text("Tap on the screen")
                    .font(.largeTitle)
                    .fontWeight(.light)
                    .padding(.top, 20)
                Spacer()
            }
        }
        .onTapGesture {
            tapAction()
        }
    }
    
    private func tapAction() {
        if percentage == 0.0 {
            self.percentage = 1.0
        } else {
            self.percentage = 0.0
        }
    }
}

#Preview {
    StrokeView()
}
